### PR TITLE
Mobile scroll bug

### LINKED ISSUE #72: [mobile safari] last 3 items in the carousel can't be selected
Weird one, I can't replicate it in devtools and it sometimes seems to trigger in chrome as well but not every time. It seems to trigger every time on click & sometimes on scroll

https://github.com/user-attachments/assets/3deb81ad-b7f8-49a4-b120-bd0ada984796

### PR DESCRIPTION
**Pull request by olicarignan**
Closes #72

### CODE REVIEW

File: src/components/pages/Homepage.jsx [hunk 1]
```diff
@@ -221,21 +223,33 @@ export default function Homepage({ homepage }) {
...
+    isMobile,
+    handleThumbnailClick,
+    activeThumbnail,
+  ]);
 
   const determineActiveThumbnail = (scrollLeft) => {
+    // Early returns for out of bounds
+    if (scrollLeft < 0) return 0;
+    if (scrollLeft >= thumbnailPositions[thumbnailPositions.length - 1])
+      return thumbnailPositions.length - 1;
```
Comment (alexismo) [inline src/components/pages/Homepage.jsx:239]: Smart to move it here!

**Review by alexismo — APPROVED** [review]
Works well!
